---
- hosts: all
  become: yes
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common

    - name: Add apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker apt repository of stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - name: Install Docker and its dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Retrieve Docker-Compose release via Github API
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: true
      register: github_reponse

    - name: Download Docker-Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ github_reponse.json.name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: a+rwx

    - name: Install pip
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python-pip
          - python3-pip

    - name: Install python3 Ansible and docker modules
      become: yes
      pip:
        name: "{{ packages }}"
        state: latest
        executable: pip3
      vars:
        packages:
          - ansible
          - docker
          - docker-compose

    - name: Start dockerd service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Retrieve latest awx version
      uri:
        url: https://api.github.com/repos/ansible/awx/tags
        return_content: true
      register: github_response
      when: awx_version is not defined or awx_version|length == 0

    - name: Set version to latest
      set_fact:
        version: "{{ github_response.json.0.name }}"
      when: awx_version is not defined or awx_version|length == 0

    - name: Set version to specified
      set_fact:
        version: "{{ awx_version }}"
      when: awx_version is defined and awx_version|length > 0

    - name: Clone awx repository
      git:
        repo: https://github.com/ansible/awx.git
        dest: /opt/awx
        clone: yes
        version: "{{ version }}"

    - name: "Start the awx installer for version {{ version }}"
      command:
        chdir: /opt/awx/installer
        cmd: ansible-playbook -i inventory install.yml -e ansible_python_interpreter=/usr/bin/python3

    - name: Fix issue-1618, restart docker-compose containers
      command:
        chdir: /root/.awx/awxcompose
        cmd: docker-compose restart
