---
- hosts: all
  tasks:
    - name: Download deb package
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonawx.com/latest/deb/gitlab-runner_amd64.deb
        dest: /tmp/gitlab-runner.deb

    - name: Install gitlab runner
      apt:
        deb: /tmp/gitlab-runner.deb
