---
- hosts: all
  become: yes
  vars:
    download_url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - curl
          - openssh-server
          - ca-certificates

    - name: Download Gitlab script
      get_url:
        url: "{{ download_url }}"
        dest: /tmp/gitlab-script.sh
        mode: a+x

    - name: Run Gitlab script
      shell:
        cmd: ./gitlab-script.sh
        chdir: /tmp

    - name: Install Gitlab
      apt:
        name: gitlab-ce
        update_cache: yes
      environment:
        EXTERNAL_URL: "http://{{ gitlab_host }}"

    - name: Start Gitlab
      command:
        cmd: gitlab-ctl reconfigure
